name: CD
# build happens when docs changes merge to master/jina docstring get updated
on:
  push:
    branches:
      - master

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Checkout to Jina core
        uses: actions/checkout@v2
        with:
          repository: jina-ai/jina
          token: ${{ secrets.JINA_DEV_BOT }}
      - name: Install released Jina version
        run: |
          pip install .  --no-cache-dir
          JINA_VERSION=$(sed -n '/^__version__/p' ./jina/__init__.py | cut -d \' -f2)-master
          RELEASE_VER=$(sed -n '/^__version__/p' ./jina/__init__.py | cut -d \' -f2)
          echo "JINA_VERSION=${JINA_VERSION}" >> $GITHUB_ENV
          echo "RELEASE_VER=${RELEASE_VER}" >> $GITHUB_ENV
          echo ${JINA_VERSION}
          echo ${RELEASE_VER}
          LAST_VER=$(git tag -l | sort -V | tail -n1)
          printf "last version: \e[1;32m$LAST_VER\e[0m\n"

